"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import "./globals.css";

export const metadata = {
  title: "Belajar Next JS",
  description: "Generated by Next.js",
};

export default function layout({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  const onClickUrl = (url: string) => {
    router.push(url);
  };

  return (
    <html lang="en">
      <head />
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        {/* <ul
          style={{
            display: "flex",
            justifyContent: "center",
            gap: "15px",
            marginTop: "15px",
            color: "blue",
            fontWeight: "bold",
          }}
        > */}
        <div className="navbar bg-base-100 flex justify-center">
          <div className="navbar-center">
            <a href="/" className="btn btn-ghost normal-case text-xl">
              Home
            </a>
            <a href="/about" className="btn btn-ghost normal-case text-xl">
              About
            </a>
            <a href="/products" className="btn btn-ghost normal-case text-xl">
              Products
            </a>
            <a href="/setting" className="btn btn-ghost normal-case text-xl">
              Settings
            </a>
          </div>
        </div>
        {/* <li
            style={{ cursor: "pointer" }}
            onClick={() => onClickUrl("/setting")}
          >
            Setting
          </li> */}
        {/* </ul> */}
        {children}
      </body>
    </html>
  );
}
