import { NextPage } from "next";
import Head from "next/head";
import styles from "@/templates/LandingPage/LandingPageTemplate.module.css";

import { H1 } from "@/templates/LandingPage/components/headings";
import { Section } from "@/templates/LandingPage/components/Section";
import { Container } from "@/templates/LandingPage/components/Container";
import { Subtitle } from "@/templates/LandingPage/components/Subtitle";
import { InlineCode } from "@/templates/LandingPage/components/InlineCode";

const Latihan: NextPage = () => {
  return (
    <>
      <Head>
        <title>Latihan</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <main>
        <Section>
          <Container center className={styles.headerSection}>
            <H1>
              <span className={styles.textGradient}>Test Lurd</span>
            </H1>
            <Subtitle>
              Belajar <InlineCode>Next JS</InlineCode> ki 🤣
            </Subtitle>
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Latihan;
